#
# The following YAML is configured to build a container inside padi-staging
# GCP project. Overwrite the following values in the pipeline
#

---
steps:
  # `docker build -t gcr.io/GCR_PROJ/APP_NAME:TAG .`
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "build", 
      "-t", "${_GCR_IMAGE}:${_TAG}", 
      "."]
 
  # Tag new docker image with SHA 
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "tag",
      "${_GCR_IMAGE}:${_TAG}",
      "${_GCR_IMAGE}:$SHORT_SHA"
    ]

  # Push built images to GCR
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_GCR_IMAGE}:${_TAG}"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_GCR_IMAGE}:$SHORT_SHA"]

substitutions:
  _TAG: latest
  _APP_NAME: "cnscp-broker"
  _GCR_PROJ: "padi-staging"
  _GCR_IMAGE: "gcr.io/${_GCR_PROJ}/${_APP_NAME}"
