version: '3'
services:
  broker:
    build: .
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "4040:4040"   # Status page port
      - "9001:9001"   # WebSocket port

