---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  ports:
    - protocol: {{ .Values.service.protocol | default "TCP" }}
      name: {{ .Values.service.portName }}
      port: {{ .Values.deployment.containerPort }}
  selector:
    app: {{ .Chart.Name }}
  type: NodePort